### PR TITLE
Added Arch support

### PR DESCRIPTION
**Pull request by B3nac**
Arch love?

### CODE REVIEW

**Comment by L1ghtn1ng** [comment]
@B3nac Thank you for submitting this. Your indentation needs fixing other than that looks good. I will test this as soon as possible.

**Comment by B3nac** [comment]
No problem glad to help. Indentation looked ok in Geany but uploaded differently. Thank you for testing it out.

**Comment by L1ghtn1ng** [comment]
It will be because you are using tabs instead of spaces

**Comment by B3nac** [comment]
I see I should have just used vim and spaces.

**Comment by L1ghtn1ng** [comment]
@B3nac yeah and its habit for me now to always use spaces which solves a lot of problems

**Comment by B3nac** [comment]
I usually do because I've programmed in Python a lot. That's what I get for not checking it out in vim first or turning off auto-indent.

**Comment by L1ghtn1ng** [comment]
Also goofile is not found in Antergos or AUR. What sub distro of arch are you using?

**Comment by B3nac** [comment]
Yeah I added the else for debugging just in case for some reason the package manager wasn't being found.

**Comment by B3nac** [comment]
I'm using regular Arch Linux but I added the blackarch repo under custom repos in /etc/pacman.conf to pull what I needed for some tools if I couldn't configure them with AUR packages. Should have specified that my bad.

**Comment by L1ghtn1ng** [comment]
Can you give me the output of of this command. Open a terminal and do the following:

* Type ```python3``` enter
* ```import platform``` enter
* Copy and paste the output of the command ```platform.linux_distribution()```

**Comment by B3nac** [comment]
('arch', '', '')

**Comment by B3nac** [comment]
I didn't realize this before but maybe I should modify the script to add the blackarch repo during setup.

**Comment by L1ghtn1ng** [comment]
Yes please

**Comment by B3nac** [comment]
I'll test my most recent change more later but that should work to install the blackarch repo. Let me know if that works out.

**Comment by L1ghtn1ng** [comment]
These need to be added to the setup as well 
* urlcrazy 
* theharvester 
* dnsrecon

I was also thinking that this might be better for adding the blackarch repo? 

```
   #Run https://blackarch.org/strap.sh as root and follow the instructions: 
    curl -O http://blackarch.org/strap.sh && sha1sum strap.sh
   
  #SHA1 sum should match: f8456229463718c097cf70ed06a806f981be7423
    sudo ./strap.sh
```

Taken from http://blackarch.org/downloads.html#install-repo

I am also hitting a snag with iceweasel. I know that is in AUR. There is another snag I am hitting with goog-mail. I should be able to easy fix that issue though but would need to make sure it did not effect kali which I dont think it will but still need to double check.

**Comment by L1ghtn1ng** [comment]
@B3nac Any update on this? Also there is conflicts that will need to be fixed also

**Comment by L1ghtn1ng** [comment]
@B3nac I am going to close this out as @leebaird has migrated setup in to update.sh which you can see here https://github.com/leebaird/discover/commit/295e74109edd048a543b84547c1bd8286414c9d4

**Pull request closed without merging**
