### PR TITLE
Replacing crt.sh calls with a Python script

### PR DESCRIPTION
**Pull request by arthurakay**
screen shot 2018-11-22 at 11 44 45 am

### CODE REVIEW

**Comment by L1ghtn1ng** [comment]
@arthurakay Thanks for the contribution if you look in mods folder there is a crt script already, would you mind adapting your PR to use that instead? Been meaning to rework that call to use the new script

**Comment by arthurakay** [comment]
I can look into it... @leebaird had specifically asked me to rewrite those lines, and I didn't realize something else already existed. I'll have to dig into that mod and digest how to use it.

**Comment by L1ghtn1ng** [comment]
@arthurakay Okay thanks and I have been out of the loop so was not a where. I did have everything ready to get it plumbed in, you will want to revert d977d12e67a2ce0240a45d837d13d4a03ce97819 that commit to get the requirements.txt file back

**Comment by leebaird** [comment]
Thanks Art !

**Pull request merged**
