### PR TITLE
Integrated my old Skipfish launcher to be part of the Discovery toolkit

### PR DESCRIPTION
**Pull request by mgeeky**
Added one function to the Discovery toolkit that integrates one of my old scripts - Skipfish launcher, that is used to construct entire, longy Skipfish command line. Should be found handy during Web pentest.

### CODE REVIEW

**Comment by L1ghtn1ng** [comment]
Hi thank you for the PR. On lines 3235-36 you are missing quotes. I will test later today

**Comment by mgeeky** [comment]
Sure, thanks for nice toolkit. 
What's wrong with the lack of quotes at pointed lines?

**Comment by L1ghtn1ng** [comment]
It's standard procedure and style guide lines. You have done it for the rest of them but not those lines

**Comment by mgeeky** [comment]
Fair enough, pushed a fixing commit.

**Comment by L1ghtn1ng** [comment]
merged, thanks

**Pull request merged**
