### PR TITLE
Moved Deprecated msfcli to msfconsole -x syntax, Other changes

### PR DESCRIPTION
**Pull request by Jsitech**
A couple of Changes:

- Moved Deprecated msfcli command to msfconsole -x syntas
- Goofile not available in Kali Sana, Setup script search for goofile and if not available Downloads goofile
- In main script Goofile runs depending on Command location, so it can be used in Kali Sana

### CODE REVIEW

**Comment by L1ghtn1ng** [comment]
The only issue I have with this is, is its pulling from Google code which is going to be deleted soon. So as to take care of this problem I suggest that we add it under the mods directory with its licence and do a check for it. If it does not find it, run it from the mods directory. Also can you check that it just does not need to be apt-get installed on Kali 2.0? I will be able to have a proper look at this PR on Tuesday next week. Thank you for your contribution.

**Comment by Jsitech** [comment]
you are totally right... I did not check with the apt-get command.....i just tested it, and it can be installed via apt-get... it never passed my mind.... silly me.... let me update......

**Comment by Jsitech** [comment]
OK, Now we are good....... Added the goofile installation of goofile to the setup script, and updated the discover script........

**Comment by L1ghtn1ng** [comment]
I still think we should have a check for it to see if it is already installed and if it is skip it other wise install it. This just gives the setup script a bit more logic and speed

**Comment by Jsitech** [comment]
OK.... put the statement as before....

**Comment by L1ghtn1ng** [comment]
Yeah

**Comment by Jsitech** [comment]
Nice tool by the way.....i didn't know about it, till i read The Hacker Playbook.....Had a free time and updated it, since i use it often.......

**Comment by L1ghtn1ng** [comment]
Thank you for the kind words, the team appreciate it. Also what version of the book is it in? As I have been wanting to get it

**Comment by Jsitech** [comment]
it's in the First Version...in the section, setting up the Penetration Testing Box.....Awesome Book... I am getting the The Hacker Playbook 2, soon........Must be a good one too.....

**Comment by L1ghtn1ng** [comment]
Thank you for the tip. Will merge this on Monday or Tuesday

**Comment by L1ghtn1ng** [comment]
merged thanks

**Comment by leebaird** [comment]
Jsitech, thanks for your help. Much appreciated.

**Pull request merged**
