### PR TITLE
Bootstrap Updates to /reports/pages.

### PR DESCRIPTION
**Pull request by iancnorden**

### CODE REVIEW

**Comment by leebaird** [comment]
Wants to say how much I appreciate this long overdue overhaul of the HTML report!

**Comment by L1ghtn1ng** [comment]
@iancnorden Can you please merge this branch with master as it has merge conflicts that need resolving before we can merge this in to master.

**Comment by L1ghtn1ng** [comment]
@iancnorden Also as a git/github tip you will always want to create a feature branch, to do your changes and not touch master at all. Master should be a copy of upstream only

**Comment by iancnorden** [comment]
Closing this for a clean PR since the most recent update from Master conflicts.

**Pull request closed without merging**
